vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        alerta_portada:
            uri_prefix: /alerta
            upload_destination: '%kernel.project_dir%/public/alerta'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        boletin_file:
            uri_prefix: /boletin
            upload_destination: '%kernel.project_dir%/public/boletin'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

